### ISSUE TITLE
Vertical Orientation

### ISSUE THREAD

**Issue by joemat04** [mmick66/KDDragAndDropCollectionView#15]
Is it possible to make the layout in vertical order, where cell will be created by one by one in rows.
Mine target to make it in cell should place in vertical order, with 1 column and independent of cell size.

**Comment by mmick66** [comment]
Is this what you are looking for?
[KDDragAndDropCollectionView.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/799120/KDDragAndDropCollectionView.zip)
