### ISSUE TITLE
Installation section & CocoaPods

### ISSUE THREAD

**Issue by lfarah** [mmick66/KDDragAndDropCollectionView#17]
Hey @mmick66, your lib is awesome but your README lacks an installation section
I created this [iOS README template](https://github.com/awesome-labs/iOS-readme-template) to help you out 😉 

I'd be cool to also add Cocoapods support. I've done this implementation myself last week for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

Please fix these issues before we can approve [the AwesomeiOS PR](https://github.com/vsouza/awesome-ios/pull/1927)

**Comment by mmick66** [comment]
I just made the edits on my README file to include a Requirements and an Installation section. I have not added Cocoa-pods support because it is really just about adding 2 files in your project, no other dependency... I hope that is ok. Please let me know...
