### ISSUE TITLE
Fast drag and drop outside

### ISSUE THREAD

**Issue by paulpasha** [mmick66/KDDragAndDropCollectionView#2]
Hello! At first, I would say thank you for that awesome extension, very helpful for my project. I downloaded your examples, and probably found a bug, and I even tried to fix that, but because I don't have a lot of experience, couldn't do that. If in collectionView function just remove "if draggingPathOfCellBeingDragged.item == indexPath.item {cell.hidden = true}" it doesn't have this bug, but looks not so good.

Problem:
When a try to drag and drop easy, everything looks good, but when I do it so much faster and do like drop outside, cell exist in new view, but hidden. For more understanding I record a video for you. Please watch this video on  https://www.dropbox.com/s/rtq0pj1771v8txg/kddragfail.mov?dl=0

**Comment by mmick66** [comment]
Thank you for the note. It was a bug indeed. I pushed a fix and changed the way the inserted cells animate in for consistency. It is trivial to change that if you do not like the fade in aesthetically.

**Comment by paulpasha** [comment]
Now looks much better! Thank you!

**Comment by paulpasha** [comment]
I just saw today that you broke one thing. When I drag and drop items, value(label) on item changes only after scrolling or when drag and drop a new one.

**Comment by mmick66** [comment]
Yes, you are right. It should be fixed now...

**Comment by paulpasha** [comment]
I just tested last commit now, and It have some bugs, see this video until the end https://www.dropbox.com/s/up56mwb7ximgxmd/bug2.mov?dl=0

**Comment by mmick66** [comment]
I pushed a fix for another but that I discovered and it seemed that I cannot reproduce your one. It could be the case that I fixed it as well but if you could please test and confirm the case I would be grateful.

**Comment by paulpasha** [comment]
Tested again and it still has a bug. Let's see this video https://www.dropbox.com/s/01om8nglusfjopp/3.mov?dl=0
00:03 - I drag and drop a cell from the second view to first view, what we see, is that in first view order numbers is fine, but in second view something wrong and we miss a number 0.
00:07 - I drag and drop again from the second view, but now it has a number 0, but miss a number 1.
When I tested drag and drop just in one of view, not between all of this views and numbers is fine, but when use a many views, something wrong.
00:33 I drag and drop all cells, now it's empty, but when I try to drag and drop back from view where I just put it, something wrong.
00:48 I try to drag and drop from third view to second view and its fixed and shows normally.

**Comment by mmick66** [comment]
Wow, thank you so much for this detailed work. 

I have made a quick fix that should take care of the first problem at 00:03 and 00:07. I cannot see to reproduce the rest after this fix so please let me know.

**Comment by paulpasha** [comment]
> I have made a quick fix that should take care of the first problem at 00:03 and 00:07.
> This is fixed now, I confirm!

Another bug on 00:33 still exist.

**Comment by mmick66** [comment]
Yes, I found what it was and it was pretty important. Basically, whatever happened in terms of dragging and dropping after the last cell was not getting registered. I pushed a fix so please check.

**Comment by paulpasha** [comment]
Yes, now you fixed that, but I found a new bug, sometimes when you do fast dragging and dropping, the snapshot is fixed in random places and not hidden. See image https://www.dropbox.com/s/v28r01nq197sqa6/kdd.png?dl=0 on first and last view all its snapshots and my finger out of the screen. Any ideas?

**Comment by mmick66** [comment]
Can you show me how to reproduce? If you could provide a video again that would be great.

**Comment by paulpasha** [comment]
I tried to record video and It is hard to show that, and I got it only twice on video. Maybe something wrong in iOS, not in your code, and in usual use it will never happen. https://www.dropbox.com/s/t22hz6q0rbxz9j7/0201.mov?dl=0 (See 00:04 and 02:22)

**Comment by mmick66** [comment]
I see what you are saying. It is hard to reproduce indeed. I cannot seem to get it from my end. I will let it go for the moment and if it annoys anyone else I might take it up again.
