### ISSUE TITLE
how to prevent to  collectionview drag

### ISSUE THREAD

**Issue by kirti301290** [mmick66/KDDragAndDropCollectionView#21]
hello
i have two  collectionview 
user can drag from one collectionview to Second collectionview but how to prevent from second collectionview to one collectionview
thanks

**Comment by mmick66** [comment]
At the moment this is not implemented. If you get some time to add it I will be very happy to merge your pull request.

**Comment by kirti301290** [comment]
i tried to  add  this functionality but unable to implemented this so if you a have time pls implement this
thanks

**Comment by mmick66** [comment]
Ok, It was a long time since I had touched the code. The functionality seems to exist. Please subclass the `KDDragAndDropCollectionView` and override
```
func canDropAtRect(_ rect : CGRect) -> Bool {
    return super.canDropAtRect && self.customCanDrop(rect)
}
func customCanDrop(_ rect : CGRect) -> Bool {
    return false
}
```
