### ISSUE TITLE
No classes or methods are public

### ISSUE THREAD

**Issue by twof** [mmick66/KDDragAndDropCollectionView#22]
None of them seem to be accessible when the lib is installed via Cocoapods. Am I missing something?

**Comment by mmick66** [comment]
Apologies. I am new to Cocoa Pods and did not realise the requirements. I will try and fix it asap. Unless you want to help out of course ;-)

**Comment by mmick66** [comment]
I tried to make some changes but now `pod spec lint` fails... Would you have some time to take a look?

**Comment by twof** [comment]
All good! I'll fork in a bit

**Comment by mmick66** [comment]
Could you do a pull request with your changes?

**Comment by twof** [comment]
Yup. Will do when I get it working

**Comment by twof** [comment]
Resolved with 
https://github.com/mmick66/KDDragAndDropCollectionView/pull/23

**Comment by mmick66** [comment]
Thanks. I merged the changes but I still get:
```
 -> KDDragAndDropCollectionViews (1.2)
    - WARN  | url: There was a problem validating the URL https://github.com/mmick66/KDDragAndDropCollectionView.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - ERROR | xcodebuild:  KDDragAndDropCollectionViews/Classes/KDDragAndDropCollectionView.swift:51:31: error: use of undeclared type 'KDDragAndDropCollectionViewDataSource'
    - ERROR | xcodebuild:  KDDragAndDropCollectionViews/Classes/KDDragAndDropCollectionView.swift:85:52: error: use of undeclared type 'KDDragAndDropCollectionViewDataSource'
    - ERROR | xcodebuild:  KDDragAndDropCollectionViews/Classes/KDDragAndDropCollectionView.swift:118:60: error: use of undeclared type 'KDDragAndDropCollectionViewDataSource'
    - ERROR | xcodebuild:  KDDragAndDropCollectionViews/Classes/KDDragAndDropCollectionView.swift:195:54: error: use of undeclared type 'KDDragAndDropCollectionViewDataSource'
    - ERROR | xcodebuild:  KDDragAndDropCollectionViews/Classes/KDDragAndDropCollectionView.swift:295:46: error: use of undeclared type 'KDDragAndDropCollectionViewDataSource'
    - ERROR | xcodebuild:  KDDragAndDropCollectionViews/Classes/KDDragAndDropCollectionView.swift:335:60: error: use of undeclared type 'KDDragAndDropCollectionViewDataSource'
```

I do not know what I changed but it seems I cannot push it as a POD. The protocol is definitely there and the project runs fine (I hate cocoapods) Any ideas?

**Comment by twof** [comment]
I think it might need to be retagged. 1.2 looks like it was before my fork.

**Comment by mmick66** [comment]
You where right! I retagged on 1.3 and it worked.. I am now getting only one warning

```
 -> KDDragAndDropCollectionViews (1.3)
    - WARN  | url: There was a problem validating the URL https://github.com/mmick66/KDDragAndDropCollectionView.
```

Any idea to what it might be?

**Comment by mmick66** [comment]
Well, it seems that the issue was [here](https://stackoverflow.com/a/48962041/1389383). Cocoa pods working again. Thanks!

**Comment by twof** [comment]
Thanks a bunch :)
