### ISSUE TITLE
Has anyone tweaked this for copying?

### ISSUE THREAD

**Issue by Tulakshana** [mmick66/KDDragAndDropCollectionView#28]
Instead of moving I would like to use this for copying items. Will it be possible to modify this to achieve that?

**Comment by mmick66** [comment]
It’s not how I built it, but you should be able to do it quite easily. Look into the delegate methods implemented in the controller. There is a delete from one array and add to the other. If you just add to the other it should do the trick.

**Comment by Tulakshana** [comment]
Thank you very much for the tip. I decided to set my deployment target to 11 and implement the native drag and drop which supports copy functionality.

**Comment by mmick66** [comment]
Damn... I am losing to Apple ;-)

**Comment by Tulakshana** [comment]
@mmick66, you just got Sherlocked by Apple :D
