### ISSUE TITLE
During dragging and when something interrupted, this happened

### ISSUE THREAD

**Issue by uypanha** [mmick66/KDDragAndDropCollectionView#29]
I'm trying to test with your sample project, and this happened when my phone vibrated while dragging the cell.
![img_f71ec5d228be-1](https://user-images.githubusercontent.com/6673987/45135493-e1d25180-b1c9-11e8-95bc-8c84f0c7731a.jpeg)

**Comment by mmick66** [comment]
Hmmm... an interesting case. I will try to have a look but cannot promise on delivery. If you manage to find a solution please do a pull request.

**Comment by uypanha** [comment]
@mmick66 Yes, I've just made the pull request with the adding features. Please checkout and accept my reqest. :-D

**Comment by mmick66** [comment]
Many thanks my friend.... merged!

**Comment by uypanha** [comment]
@mmick66 You're welcome, I'll distribute more if I find it's useful...!
