### ISSUE TITLE
KDDragAndDropCollectionView inheritance

### ISSUE THREAD

**Issue by alednik** [mmick66/KDDragAndDropCollectionView#30]
Is ti possible to change access modifier for class  KDDragAndDropCollectionView from 'public' to 'open', to provide the possibility of inheritance from KDDragAndDropCollectionView?

**Comment by mmick66** [comment]
Please do so and add a pull request.

**Comment by netspencer** [comment]
This has been changed but the new version doesn't seem to be on CocoaPods. Any way that master could be turned into a new version and published to CocoaPods?

**Comment by mmick66** [comment]
I just bumped the version to 1.5.2. I think that will solve the issue. Please let me know if it does not.
