### ISSUE TITLE
inside ScrollView implementation 

### ISSUE THREAD

**Issue by ghost** [mmick66/KDDragAndDropCollectionView#4]
Hi There, Thanks for awesome extension and your great work! 

I am implementing this for my `UITableView` where each cell is a CollectionView, however `KDDragAndDropManager` only works for the initial visible cells, If I scroll and load  new cells, those collectionViews will not be droppable. 

Can you suggest a place that I can look deeper to address the issue. 

Cheers

**Comment by ghost** [comment]
Update : I fixed this issue by passing the `tableView` for canvas: when instantiating  `KDDragAndDropManager`

**Comment by mmick66** [comment]
I was thinking of extending my class to UITableViews. Could you send a pull request to view what you have done and I might include it in the project.
