### ISSUE TITLE
Create new section

### ISSUE THREAD

**Issue by rajeshkumar-l-2098** [mmick66/KDDragAndDropCollectionView#5]
While Drag the cell I can't create a new section.

**Comment by mmick66** [comment]
That is correct. You can drag between existing sections however. 

I guess you want to create a new section while dragging to the end of the collection view. Am I right? 

How do you imagine the functionality? How would the user decide if he wants to create a new section?

**Comment by rajeshkumar-l-2098** [comment]
Just imagine section with categories(like Fruits, vegetables). If I want to drag a cell and create another category, I need to create a new section on drag.

**Comment by mmick66** [comment]
Yes, I understand that. However, that would be confusing for users that simply want to drag to the end of a list. I do not see any way to inform users about what they are about to do and the most logical assumption is that you are simply dragging at the end of the list.

**Comment by rajeshkumar-l-2098** [comment]
Yes, I understand.
