### ISSUE TITLE
Error when dragging cell out of collectionView

### ISSUE THREAD

**Issue by neilsekhon** [mmick66/KDDragAndDropCollectionView#8]
For some reason when I implemented the exact same files into my own project, I am getting this issue whenever I drag a cell out of a collection view:

‘Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (21) must be equal to the number of items contained in that section before the update (21), plus or minus the number of items inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).’

I set up the storyboard the exact same way as the example project, but I can't seem to figure out this issue. Thanks, Neil

**Comment by mmick66** [comment]
Are you implementing the delegates that are responsible for updating the actual data?

**Comment by neilsekhon** [comment]
I think so, but it looks like the problem is in the data source. The crash happens in the willMoveItem function. In my project, the dragDropDataSource just shows my view controller in the debugger, but in the example project it shows the three collection views, the data, and the dragAndDropManager as well. I'm pretty inexperienced so I'm not sure what this means.

**Comment by mmick66** [comment]
Have a look at the [guide](https://github.com/mmick66/KDDragAndDropCollectionView#quick-guide). You need to implement a part of the protocol so that when you move items around, delete or add them you update the model first.

PS. I saw your post on my blog and since we are discussing it here I took the courage of deleting it from there.

**Comment by neilsekhon** [comment]
I used the exact same files from the example. Here are pictures of the debugger in the willMoveItem function in the example project vs my project 
![img_3662](https://cloud.githubusercontent.com/assets/13142423/13752339/a5c6c46e-e9e4-11e5-8e4a-218fa2a5e837.JPG)
![img_3661](https://cloud.githubusercontent.com/assets/13142423/13752343/ab51386a-e9e4-11e5-9d19-e76d3681417c.JPG)

**Comment by mmick66** [comment]
Can you please send my a zipped file of your project? I might have some time to have a look.

**Comment by neilsekhon** [comment]
[TestKDCollectionView.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/176994/TestKDCollectionView.zip)

**Comment by mmick66** [comment]
Ok, if you look at the guidelines you will see that I used the collection view's tag as an index to the data. It is just for testing purposes and you should create your own strategy to pick the correct data depending on the collection view.

[TestKDCollectionView.zip](https://github.com/mmick66/KDDragAndDropCollectionView/files/179258/TestKDCollectionView.zip)
